apiVersion: v1
kind: PersistentVolume
metadata:
  name: tourbox-code-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/vincent/dev/tbx/app-api/
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tourbox-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: tourbox-code-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourbox-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourbox-api-app
  template:
    metadata:
      labels:
        app: tourbox-api-app
    spec:
      containers:
      - name: tourbox-api-container
        image: tourbox-api-debug:latest
        imagePullPolicy: IfNotPresent
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 15
        volumeMounts:
          - name: tourbox-code-volume
            mountPath: /var/www/html
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
        - containerPort: 80  # Application port
        - containerPort: 9967 # Xdebug port
      volumes:
        - name: tourbox-code-volume
          persistentVolumeClaim:
            claimName: tourbox-code-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tourbox-api-service
spec:
  selector:
    app: tourbox-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 # exposed outside cluster
  type: NodePort